taoshidev/request-network

src/controller/payment.controller.ts
src/db/dto/stripe-check.dto.ts

feat(payment.controller): send configured rn url to be checked during stripe activation

---

package.json

chore(version): upgrade to v1.4.5

---

package.json
src/controller/payment.controller.ts
src/db/dto/stripe-check.dto.ts

Release v1.4.5

---

deploy/task-definition-staging-app.json
deploy/task-definition-staging-cron.json

fix(task-definition): remove role env

---

package.json
src/utils/logger.ts

chore(version): up version to 1.4.6

---

deploy/task-definition-staging-app.json
deploy/task-definition-staging-cron.json
package.json
src/utils/logger.ts

Release v1.4.6

---

src/controller/payment.controller.ts
src/core/registration.ts
src/db/dto/stripe-check.dto.ts
src/service/stripe.manager.ts

feat(stripe): check if stripe keys are for live environment

---

package.json

chore(version): update version

---

package.json
src/controller/payment.controller.ts
src/core/registration.ts
src/db/dto/stripe-check.dto.ts
src/service/stripe.manager.ts

Release v1.4.7

---

DATA_PURCHASER.md
package.json
src/auth/auth.ts
src/auth/consumer-request.ts
src/core/request.ts

fix(error): remove throw error, send res

---

DATA_PURCHASER.md
package.json
src/auth/auth.ts
src/auth/consumer-request.ts
src/core/request.ts

Release v1.4.9

---

src/service/stripe.manager.ts

https://sataoshi.atlassian.net/browse/TE-310

feat(stripe.manager): send transaction info for payment email

---

src/service/stripe.manager.ts

https://sataoshi.atlassian.net/browse/TE-310

feat(stripe.manager): find existing customers on stripe

---

package.json

chore(release): up version number

---

package.json
src/service/stripe.manager.ts

Release v1.4.10

---

src/controller/consumer.controller.ts
src/controller/payment.controller.ts
src/controller/paypal.controller.ts
src/db/dto/paypal-product.dto.ts
src/db/dto/service.dto.ts
src/db/migrations/0025_ambiguous_revanche.sql
src/db/migrations/0026_fast_silhouette.sql
src/db/migrations/0027_salty_tana_nile.sql
src/db/migrations/meta/0025_snapshot.json
src/db/migrations/meta/0026_snapshot.json
src/db/migrations/meta/0027_snapshot.json
src/db/migrations/meta/_journal.json
src/db/schema.ts
src/public/paypal.js
src/service/paypal-product.manager.ts
src/service/paypal.manager.ts
src/service/stripe.manager.ts

https://sataoshi.atlassian.net/browse/TE-307

feat(paypal): cancel subscription

---

package.json
src/auth/payment-request.ts
src/controller/consumer.controller.ts
src/controller/payment.controller.ts
src/service/paypal.manager.ts

fix(app): fix all imports using src

---

src/auth/payment-request.ts
src/service/stripe.manager.ts

fix(payments): set service after token check

---

package.json

chore(version): version update

---

package.json
src/public/stripe.js

feat(stripe): always display two decimals on price

---

package.json
src/public/stripe.js
src/service/stripe.manager.ts

fix(stripe): convert to int before sending

---

package.json
src/public/stripe.js
src/service/stripe.manager.ts

Release v1.4.15

---

package.json
src/auth/auth.ts

fix(url): fix url check for unkey

---

package.json
src/auth/auth.ts

* fix(fix): unkey url check to match current server
* fix(url): fix url check for unkey

Release v1.4.16

---

package.json
src/auth/auth.ts
src/db/dto/consumer.dto.ts
src/index.ts

Release v1.4.17

---

package.json
src/core/database.wrapper.ts
src/db/migrate.ts
src/public/paypal.js
src/public/stripe.js
src/service/paypal.manager.ts
src/utils/sentry-helper.ts

refactor(code): add helper to capture sentry err
